### ISSUE TITLE
Regression w/ `arc_select()` returning data.frame not sf objects

### ISSUE THREAD

**Issue by elipousson** [R-ArcGIS/arcpbf#1]
**Describe the bug**

Using the latest version of arcgislayers, `arc_select()` is returning a data.frame instead of an sf object. I haven't dug into the details but I suspect it is related to this PR https://github.com/R-ArcGIS/arcgislayers/pull/197/

**To Reproduce**

``` r
library(arcgislayers)

bikeways_url <- "https://services.arcgis.com/njFNhDsUCentVYJW/arcgis/rest/services/Bikeways_Application_gdb/FeatureServer/0"

bikeways_data <- arc_read(bikeways_url)

class(bikeways_data)
#> [1] "data.frame"
```

``` r

bikeways_layer <- arc_open(bikeways_url)

class(arc_select(bikeways_layer))
#> [1] "data.frame"
```

<sup>Created on 2024-07-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Expected behavior**

The url should return a sf object.

**Additional context**

The tests should be updated to make sure this type of regression would get caught in the future.

**Comment by JosiahParry** [comment]
@elipousson in about an hour can you update `{arcpbf}` from https://r-arcgis.r-universe.dev/arcpbf? If that works for you ill push an update to CRAN.

**Comment by elipousson** [comment]
@JosiahParry Tried it and got it working! I can double-check later if I needed to wait an hour exactly. Always good news when a bug report is a real bug and not just user error. Especially when the bug is a relatively quick fix.

**Comment by JosiahParry** [comment]
Awesome! The one hour this is because r-universe rebuilds binaries on an hour schedule if there has been a change

**Comment by elipousson** [comment]
Did you want me to add a test with expect_s3_class to check for an sf output? This is probably a one and done fix but would be good to get the expected class output into the text coverage.

**Comment by JosiahParry** [comment]
Sure! That’s not a bad idea! The challenge is being able to test having different packages available

**Comment by JosiahParry** [comment]
@elipousson new version of arcpbf hit CRAN this morning. Please let me know if it all goes well
